
#       SITE BASICS

url: "https://localhost:4000"
baseurl: "" # Deploying to root domain

theme: null
minimal_mistakes_skin: noirbloom # hardcoded into main.scss

navigation: # Top Menubar _data/navigation.yml
  custom: true
logo: # Display in masthead, e.g. "/assets/images/88x88.png"

teaser: # Fallback teaser image, e.g. "/assets/images/500x300.png"

author: # Author Information _data/config-text.yml
  avatar: "/assets/images/avatar.png"
  links:
    - icon: "far fa-fw fa-envelope"
      url: mailto:youremail@example.com
    - icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/yourprofile
    - icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/yourprofile



#       PLUGINS

plugins:
  - jekyll-minifier
  - jekyll-polyglot
  - jekyll-include-cache
# for later...
# - jekyll-feed
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-redirect-from


#       FOOTER LINKS

footer:
  links:
    - label: "Email"
      icon: "fa-solid fa-fw fa-envelope"
      url: mailto:youremail@example.com
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/yourprofile
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/yourprofile


#      LANGUAGES - POLYGLOT

languages: 
  - en
  - he
default_lang: en
exclude_from_localization:
  - assets/js
  - assets/images
  - assets/css
parallel_localization: false
lang_from_path: false

markdown: kramdown # Syntax Processing
highlighter: rouge # Code Highlighting


#      COLLECTIONS

collections:
  places:
    output: true
    localize: true
  posts:
    output: true
    localize: true


#   CONTENT LANGUAGE AND PERMALINKS

defaults:
  - scope: # English places
      path        : "_places/en"
      type        : places
    values:
      permalink   : /:name/
      locale      : en
      lang        : en

  - scope: # Hebrew Pages
      path        : "_places/he"
      type        : places
    values:
      permalink   : /:name/
      locale      : he
      lang        : he
      rtl         : true
  - scope: # English Posts
      path        : "_posts/en"
      type        : posts
    values:
      permalink   : /posts/:title/
      locale      : en
      lang        : en
  - scope: # Hebrew Posts
      path        : "_posts/he"
      type        : posts
    values:
      permalink   : /posts/:title/
      locale      : he
      lang        : he
      rtl         : true


#     MORE BUILD SETTINGS

include:
 - _pages/en
 - _pages/he
 - _posts/en
 - _posts/he
 - assets/css/custom.css
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - feed.xml
  - zeevsh.code-workspace
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - CHANGELOG.md
  - LICENSE
  - package.json
  - Rakefile
  - LINKS

sass:
  quiet_deps: true
  sourcemap: never
  style: compressed

jekyll-minifier:
  compress_html:
    clippings: [html, head, body]
    comments: all
    endings: all
    profile: false
    blanklines: true
  ignore:
      envs: [development]
  uglifier_args:
    harmony: true
  exclude:
    - assets/js/main.min.js
    - assets/js/vendor
    - assets/js/plugins