#       SITE BASICS

url: "https://localhost:4000"
baseurl: "" # Deploying to root domain

theme: null
minimal_mistakes_skin: noirbloom # hardcoded into main.scss

navigation: # Top Menubar _data/navigation.yml
  custom: true
logo: # Display in masthead, e.g. "/assets/images/88x88.png"

teaser: # Fallback teaser image, e.g. "/assets/images/500x300.png"

author: # Author Information _data/config-text.yml
  avatar: "/assets/images/avatar.png"
  links:
    - icon: "far fa-fw fa-envelope"
      url: mailto:youremail@example.com
    - icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/yourprofile
    - icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/yourprofile



#       PLUGINS

plugins:
# - jekyll-minifier
# - jekyll-polyglot
  - jekyll-include-cache
# for later...
# - jekyll-feed
# - jekyll-seo-tag
# - jekyll-sitemap
# - jekyll-redirect-from


#       FOOTER LINKS

footer:
  links:
    - label: "Email"
      icon: "fa-solid fa-fw fa-envelope"
      url: mailto:youremail@example.com
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: https://www.facebook.com/yourprofile
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/yourprofile


#      LANGUAGES - POLYGLOT


# languages:
#  - en
#  - he
# default_lang: en
# exclude_from_localization:
# - assets/js
# - assets/images
# - assets/css
# - login.md
#parallel_localization: false


markdown: kramdown # Syntax Processing
highlighter: rouge # Code Highlighting


#      COLLECTIONS

collections:
  places:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /posts/:title/


#   CONTENT LANGUAGE AND PERMALINKS

defaults:
  - scope:
      path: ""
    values:
      lang: "en"
      rtl: false
  - scope:
      path: "**/*-he.md"
    values:
      lang: "he"
      rtl: true


#     MORE BUILD SETTINGS

include:
 #- _places
 #- _posts
 - assets/css/custom.scss
exclude:
  - build_pages.rb
  - #_places/_content/
  - #_posts/_content/
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - feed.xml
  - zeevsh.code-workspace
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - CHANGELOG.md
  - LICENSE
  - package.json
  - Rakefile
  - LINKS

sass:
  quiet_deps: true
  sourcemap: never
  style: compressed

jekyll-minifier:
  compress_html:
    clippings: [html, head, body]
    comments: all
    endings: all
    profile: false
    blanklines: true
  ignore:
      envs: [development]
  uglifier_args:
    harmony: true
  exclude:
    - assets/js/main.min.js
    - assets/js/vendor
    - assets/js/plugins