en:
  title                      : "Zeev Does Things"
  subtitle                   : "A blog about various topics"
  name                       : "Ze Ev Shalev"
  description              : "I'm a creative, curious human."
  copyright                 : "© 2023 Ze Ev Shalev. All rights reserved."
  copyright_url             : "https://zeev.shalev.io"
  author_name               : "Ze Ev Shalev"
  author_bio                 : "I'm a creative, curious human."
  author_location           : "Earth"
  email_label                : "Email"
  instagram_label           : "Instagram"
  facebook_label           : "Facebook"
  mastodon_label: "Mastodon"

he:
  title                      : "זאב עושה דברים"
  subtitle                   : "בלוג על נושאים שונים"
  name                       : "זאב שלו"
  description              : "אני אדם יצירתי וסקרן."
  copyright                 : "© 2023 Ze Ev Shalev. All rights reserved."
  copyright_url             : "https://zeev.shalev.io"
  author_name               : "זאב שלו"
  author_bio                 : "אני אדם יצירתי וסקרן."
  author_location           : "ארץ"
  email_label                : "אימייל"
  instagram_label           : "אינסטגרם"
  facebook_label           : "פייסבוק"
  mastodon_label : "מאסטודון"
